name: Push Stack Image

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  push:
    name: Push
    runs-on: ubuntu-22.04
    steps:
      - name: Parse Event
        id: event
        run: |
          echo "tag=$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)" >> "$GITHUB_OUTPUT"
          # echo "build_download_url=$(jq -r '.release.assets[] | select(.name | endswith("build.oci")) | .url' "${GITHUB_EVENT_PATH}")" >> "$GITHUB_OUTPUT"
          # echo "run_download_url=$(jq -r '.release.assets[] | select(.name | endswith("run.oci")) | .url' "${GITHUB_EVENT_PATH}")" >> "$GITHUB_OUTPUT"
          echo "run_nodejs_16_download_url=$(jq -r '.release.assets[] | select(.name | endswith("run-nodejs-16.oci")) | .url' "${GITHUB_EVENT_PATH}")" >> "$GITHUB_OUTPUT"
          # echo "run_nodejs_18_download_url=$(jq -r '.release.assets[] | select(.name | endswith("run-nodejs-18.oci")) | .url' "${GITHUB_EVENT_PATH}")" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Download nodejs-16 Run Image
        uses: paketo-buildpacks/github-config/actions/release/download-asset@main
        with:
          url: ${{ steps.event.outputs.run_nodejs_16_download_url }}
          output: "/github/workspace/run-nodejs-16.oci"
          token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

      - name: Get Registry Repo Name
        id: registry-repo
        run: |
          # Strip off the Github org prefix and 'stack' suffix from repo name
          # paketo-buildpacks/some-name-stack --> some-name
          echo "name=$(echo "${{ github.repository }}" | sed 's/^.*\///' | sed 's/\-stack$//')" >> "$GITHUB_OUTPUT"

      - name: Push to DockerHub
        id: push
        env:
          DOCKERHUB_USERNAME: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}
          DOCKERHUB_ORG: "paketocommunity"
          GCR_USERNAME: _json_key
          GCR_PROJECT: "paketo-community"
        run: |
          echo "${DOCKERHUB_PASSWORD}" | sudo skopeo login --username "${DOCKERHUB_USERNAME}" --password-stdin index.docker.io
          echo "${GCR_PASSWORD}" | sudo skopeo login --username "${GCR_USERNAME}" --password-stdin gcr.io

          sudo skopeo copy "oci-archive:${GITHUB_WORKSPACE}/run-nodejs-16.oci" "docker://${DOCKERHUB_ORG}/${{ steps.registry-repo.outputs.name }}-run-nodejs-16:${{ steps.event.outputs.tag }}"
          sudo skopeo copy "oci-archive:${GITHUB_WORKSPACE}/run-nodejs-16.oci" "docker://${DOCKERHUB_ORG}/${{ steps.registry-repo.outputs.name }}-run-nodejs-16:latest"

  failure:
    name: Alert on Failure
    runs-on: ubuntu-22.04
    needs: [push]
    if: ${{ always() && needs.push.result == 'failure' }}
    steps:
      - name: File Failure Alert Issue
        uses: paketo-buildpacks/github-config/actions/issue/file@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          label: "failure:push"
          comment_if_exists: true
          issue_title: "Failure: Push Image workflow"
          issue_body: |
            Push Image workflow [failed](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}).
            Please take a look to ensure CVE patches can be released. (cc @paketo-buildpacks/stacks-maintainers).
          comment_body: |
            Another failure occurred: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
